# Generated by Django 2.0.4 on 2018-04-25 20:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_body',
            field=ckeditor.fields.RichTextField(default='empty'),
            preserve_default=False,
        ),
    ]
